import { NextResponse } from 'next/server';
import prisma from '@/prisma/db';
import { getSettings } from '@/lib/settings';
import {
  createIssue,
  getBranchSha,
  createBranch,
  createOrUpdateFile,
  createPullRequest,
} from '@/lib/github';

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  // Load test with all data
  const test = await prisma.test.findUnique({
    where: { id },
    include: {
      variants: { include: { events: true } },
      project: true,
    },
  });

  if (!test) {
    return NextResponse.json({ error: 'Test not found' }, { status: 404 });
  }

  // Get settings
  const settings = getSettings();
  if (!settings.githubToken || !settings.githubRepo) {
    return NextResponse.json(
      { error: 'GitHub not configured. Go to Settings and add your token + repo.' },
      { status: 400 }
    );
  }

  const { githubToken: token, githubRepo: repo, githubBranch: baseBranch = 'main' } = settings;

  // Parse request body for winner selection
  const body = await request.json().catch(() => ({}));
  const winnerId = body.winnerId || test.winnerId;
  const winner = test.variants.find((v) => v.id === winnerId);

  if (!winner) {
    return NextResponse.json({ error: 'No winner selected. Declare a winner first.' }, { status: 400 });
  }

  // Compute stats for each variant
  const variantStats = test.variants.map((v) => {
    const views = v.events.filter((e) => e.type === 'view').length;
    const conversions = v.events.filter((e) => e.type === 'conversion').length;
    const rate = views > 0 ? ((conversions / views) * 100).toFixed(2) : '0.00';
    return { ...v, views, conversions, rate };
  });

  const control = variantStats[0];
  const winnerStats = variantStats.find((v) => v.id === winnerId)!;
  const lift =
    parseFloat(control.rate) > 0
      ? (((parseFloat(winnerStats.rate) - parseFloat(control.rate)) / parseFloat(control.rate)) * 100).toFixed(1)
      : 'N/A';

  // Determine content type label
  let contentTypeLabel = test.contentType || 'text';
  try {
    const parsed = JSON.parse(winner.content);
    if (parsed.type === 'position') contentTypeLabel = 'reposition';
  } catch {}
  if (winner.content.startsWith('MERMAID:')) contentTypeLabel = 'diagram';
  if (winner.content.startsWith('GAME:')) contentTypeLabel = 'game';

  // ---- Build rich markdown documentation ----
  const now = new Date().toISOString().split('T')[0];
  const slug = test.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const branchName = `ab-test/${slug}-${id.slice(0, 8)}`;

  const statsTable = variantStats
    .map(
      (v) =>
        `| ${v.name} | ${v.views} | ${v.conversions} | ${v.rate}% | ${v.id === winnerId ? '**Winner**' : ''} |`
    )
    .join('\n');

  const issueBody = `# A/B Test Report: ${test.name}

## Overview

| Field | Value |
|-------|-------|
| **Test ID** | \`${test.id}\` |
| **Project** | ${test.project.name} (${test.project.url}) |
| **Element** | \`${test.fingerprint}\` |
| **Content Type** | ${contentTypeLabel} |
| **Goal** | ${test.goal} |
| **Status** | Finalized |
| **Date** | ${now} |

## Results

| Variant | Views | Conversions | CVR | Result |
|---------|-------|-------------|-----|--------|
${statsTable}

**Lift**: ${lift}% improvement over control

## Test Flow

\`\`\`mermaid
flowchart LR
    V[Visitor] --> S{50/50 Split}
    S --> C[Control<br/>${control.views} views<br/>${control.rate}% CVR]
    S --> W[${winner.name}<br/>${winnerStats.views} views<br/>${winnerStats.rate}% CVR]
    W --> R[Winner ✓]
    style W fill:#22c55e,color:#fff
    style R fill:#16a34a,color:#fff
\`\`\`

## Conversion Funnel

\`\`\`mermaid
flowchart TD
    A[Total Views: ${variantStats.reduce((s, v) => s + v.views, 0)}] --> B[Split Traffic]
${variantStats.map((v) => `    B --> ${v.name.replace(/\s/g, '')}[${v.name}<br/>${v.views} views]`).join('\n')}
${variantStats.map((v) => `    ${v.name.replace(/\s/g, '')} --> ${v.name.replace(/\s/g, '')}C[${v.conversions} conversions<br/>${v.rate}% CVR]`).join('\n')}
\`\`\`

## Winning Variant Details

**Type**: ${contentTypeLabel}
**Content**:
\`\`\`
${winner.content.length > 2000 ? winner.content.slice(0, 2000) + '...' : winner.content}
\`\`\`

${winner.metadata ? `**AI Generation Metadata**:\n\`\`\`json\n${winner.metadata}\n\`\`\`` : ''}

## Implementation

This test result has been implemented in PR linked below. The winning variant should replace the control on \`${test.fingerprint}\`.

---
*Generated by A/B Engine — AI-Powered Testing*
`;

  // ---- Build implementation file ----
  const implementationContent = buildImplementation(test, winner, contentTypeLabel);

  try {
    // Create GitHub Issue
    const issue = await createIssue(
      token,
      repo,
      `[A/B Test] ${test.name} — ${winner.name} wins with ${lift}% lift`,
      issueBody,
      ['ab-test', 'documentation'],
    );

    // Create branch + PR
    const baseSha = await getBranchSha(token, repo, baseBranch);
    await createBranch(token, repo, branchName, baseSha);

    // Commit implementation file
    await createOrUpdateFile(
      token,
      repo,
      `ab-tests/${slug}.md`,
      issueBody,
      `docs: A/B test report for "${test.name}"`,
      branchName,
    );

    await createOrUpdateFile(
      token,
      repo,
      `ab-tests/${slug}-implementation.js`,
      implementationContent,
      `feat: implement winning variant for "${test.name}"`,
      branchName,
    );

    // Create PR
    const pr = await createPullRequest(
      token,
      repo,
      `[A/B Test] Implement winner: ${test.name}`,
      `## A/B Test Implementation\n\nCloses #${issue.number}\n\n**Test**: ${test.name}\n**Winner**: ${winner.name} (${winnerStats.rate}% CVR, ${lift}% lift)\n**Type**: ${contentTypeLabel}\n\n### What this PR does\n- Adds test report documentation\n- Adds implementation snippet to apply the winning variant\n\n### Test Flow\n\`\`\`mermaid\nflowchart LR\n    V[Visitor] --> S{50/50 Split}\n    S --> C[Control<br/>${control.rate}% CVR]\n    S --> W[${winner.name}<br/>${winnerStats.rate}% CVR]\n    W --> R[Winner ✓]\n    style W fill:#22c55e,color:#fff\n\`\`\`\n\n---\n*Generated by A/B Engine*`,
      branchName,
      baseBranch,
    );

    // Mark test as completed with winner
    await prisma.test.update({
      where: { id },
      data: { status: 'completed', winnerId },
    });

    return NextResponse.json({
      success: true,
      issue: { number: issue.number, url: issue.html_url },
      pr: { number: pr.number, url: pr.html_url },
      branch: branchName,
    });
  } catch (e: any) {
    console.error('Finalize error:', e);
    return NextResponse.json({ error: e.message || 'Failed to create GitHub resources' }, { status: 500 });
  }
}

function buildImplementation(
  test: any,
  winner: any,
  contentType: string,
): string {
  const selector = test.fingerprint;

  if (contentType === 'reposition') {
    let pos: any;
    try { pos = JSON.parse(winner.content); } catch { pos = {}; }
    return `/**
 * A/B Test Winner Implementation: ${test.name}
 * Type: Reposition
 *
 * The winning variant moves the element to a new position in the DOM.
 * Add this script to your page to apply the change permanently.
 */
(function() {
  const el = document.querySelector(${JSON.stringify(selector)});
  if (!el) return;

  const newParent = document.querySelector(${JSON.stringify(pos.parentSelector || 'body')});
  ${pos.beforeSelector ? `const before = document.querySelector(${JSON.stringify(pos.beforeSelector)});` : 'const before = null;'}

  if (newParent) {
    newParent.insertBefore(el, before);
  }
})();
`;
  }

  if (contentType === 'diagram') {
    const mermaidCode = winner.content.replace(/^MERMAID:/, '');
    return `/**
 * A/B Test Winner Implementation: ${test.name}
 * Type: Mermaid Diagram
 *
 * The winning variant replaces text content with a Mermaid diagram.
 * Requires Mermaid.js to be loaded on the page.
 */
(function() {
  const el = document.querySelector(${JSON.stringify(selector)});
  if (!el) return;

  // Load Mermaid if not already loaded
  if (!window.mermaid) {
    const script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js';
    script.onload = function() {
      window.mermaid.initialize({ startOnLoad: false, theme: 'default' });
      render();
    };
    document.head.appendChild(script);
  } else {
    render();
  }

  function render() {
    const container = document.createElement('div');
    container.className = 'mermaid';
    container.textContent = ${JSON.stringify(mermaidCode)};
    el.replaceWith(container);
    window.mermaid.run({ nodes: [container] });
  }
})();
`;
  }

  if (contentType === 'game') {
    const gameCode = winner.content.replace(/^GAME:/, '');
    return `/**
 * A/B Test Winner Implementation: ${test.name}
 * Type: Game (OCS GameEngine)
 *
 * The winning variant replaces content with an interactive game level.
 * Requires the OCS GameEngine to be available.
 */
// Game level module code:
${gameCode}
`;
  }

  if (contentType === 'button') {
    let bc: any;
    try { bc = JSON.parse(winner.content); } catch { bc = { text: winner.content }; }
    return `/**
 * A/B Test Winner Implementation: ${test.name}
 * Type: Button
 *
 * Apply winning button styles and text.
 */
(function() {
  const el = document.querySelector(${JSON.stringify(selector)});
  if (!el) return;

  ${bc.text ? `el.textContent = ${JSON.stringify(bc.text)};` : ''}
  ${bc.backgroundColor ? `el.style.backgroundColor = ${JSON.stringify(bc.backgroundColor)};` : ''}
  ${bc.textColor ? `el.style.color = ${JSON.stringify(bc.textColor)};` : ''}
  ${bc.borderRadius ? `el.style.borderRadius = ${JSON.stringify(bc.borderRadius)};` : ''}
  ${bc.padding ? `el.style.padding = ${JSON.stringify(bc.padding)};` : ''}
  ${bc.fontSize ? `el.style.fontSize = ${JSON.stringify(bc.fontSize)};` : ''}
})();
`;
  }

  if (contentType === 'html' || contentType === 'hero') {
    return `/**
 * A/B Test Winner Implementation: ${test.name}
 * Type: ${contentType}
 *
 * Replace element content with winning HTML variant.
 */
(function() {
  const el = document.querySelector(${JSON.stringify(selector)});
  if (!el) return;

  el.innerHTML = ${JSON.stringify(winner.content)};
})();
`;
  }

  // Default: text
  return `/**
 * A/B Test Winner Implementation: ${test.name}
 * Type: Text
 *
 * Replace element text with the winning variant.
 */
(function() {
  const el = document.querySelector(${JSON.stringify(selector)});
  if (!el) return;

  el.innerText = ${JSON.stringify(winner.content)};
})();
`;
}
